
[package]
name = "xtra-kernel"
version = "0.0.0"
edition = "2021"
authors = ["Chloë Strainge <nullptr.0@gmail.com>"]
description = "The main kernel crate for xtra-os."
license = "MIT"


[target.riscv64imac-unknown-none-elf]
rustflags = [ "-C", "relocation-model=pic", "-C", "link-arg=-pie" ]
